---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# hetoolkit

<!-- badges: start -->
<!-- badges: end -->

The `hetoolkit` package comprises a collection of functions for assembling, processing, visualising and modelling hydro-ecological data.  

## Installation

To install the latest release of `hetoolkit` use the following code:

``` r
remotes::install_github("APEM-LTD/hetoolkit")

```

## Overview

The `hetoolkit` package comprises a collection of functions for assembling, processing, visualising and modelling hydro-ecological data.  The package was developed by APEM LTD on behalf on the Environment Agency; any further bug-fixing or modification to the package will be overseen by the Environment Agency.

## Examples

Further information on the functions contained within the package, including examples, can be found in the `HE Toolkit - Vingette` at https://apem-ltd.github.io/hetoolkit/.

## Reporting Bugs

Please consider reporting bugs and asking questions on the Issues page.


## References

FBA, 2020. River Invertebrate Classification Tool (RICT2) User Guide V1.5 (2020) [Online] Available at: https://www.fba.org.uk/FBA/Public/Discover-and-Learn/Projects/User%20Guides.aspx



